# Generated by Django 5.0.2 on 2024-02-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='lnmae',
            new_name='lname',
        ),
    ]
