# Generated by Django 5.0.2 on 2024-02-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_fff'),
    ]

    operations = [
        migrations.AddField(
            model_name='fff',
            name='det',
            field=models.CharField(max_length=234, null=True),
        ),
    ]
